quizz_questions = {
    "What is the capital of France?": "Paris",
    "What is 5 + 7?": "12",
    "Which planet is known as the Red Planet?": "Mars",
    "Who wrote Hamlet?": "Shakespeare",
    "What is the largest ocean on Earth?": "Pacific Ocean",
    "What color do you get by mixing red and white?": "Pink",
    "How many days are there in a week?": "7",
    "What is the boiling point of water in Celsius?": "100",
    "Which animal is known as the King of the Jungle?": "Lion",
    "What is the square root of 81?": "9",
    "Which language is primarily used for web development?": "JavaScript",
    "Who painted the Mona Lisa?": "Leonardo da Vinci",
    "What is the smallest prime number?": "2",
    "Which gas do plants absorb from the atmosphere?": "Carbon Dioxide",
    "What is the capital of Japan?": "Tokyo",
    "How many continents are there?": "7",
    "Which organ pumps blood in the human body?": "Heart",
    "What is 15 multiplied by 3?": "45",
    "Which bird is known for mimicking sounds?": "Parrot",
    "What is the freezing point of water in Celsius?": "0",
    "Who discovered gravity?": "Isaac Newton",
    "What is the largest mammal?": "Blue Whale",
    "Which country is famous for pizza?": "Italy",
    "How many hours are there in a day?": "24",
    "What is the chemical symbol for gold?": "Au",
    "Which instrument has six strings?": "Guitar",
    "What is 100 divided by 4?": "25",
    "Which planet is closest to the Sun?": "Mercury",
    "Who invented the telephone?": "Alexander Graham Bell",
    "What is the capital of India?": "New Delhi",
    "How many legs does a spider have?": "8",
    "What is the hardest natural substance?": "Diamond",
    "Which festival is known as the festival of lights in India?": "Diwali",
    "What is the currency of the USA?": "Dollar",
    "Which animal is the tallest?": "Giraffe",
    "What is 9 squared?": "81",
    "Who wrote Harry Potter?": "J.K. Rowling",
    "Which planet has rings?": "Saturn",
    "What is the main language spoken in Brazil?": "Portuguese",
    "How many minutes are there in one hour?": "60",
    "Which vitamin is produced by sunlight?": "Vitamin D",
    "What is the capital of Australia?": "Canberra",
    "Which animal can live both in water and on land?": "Frog",
    "What is 50 percent of 200?": "100",
    "Which metal is liquid at room temperature?": "Mercury",
    "Who was the first man on the Moon?": "Neil Armstrong",
    "What is the national sport of India?": "Hockey",
    "Which shape has three sides?": "Triangle",
    "How many teeth does an adult human usually have?": "32",
    "What is the largest desert in the world?": "Sahara Desert",
    "Which device is used to measure temperature?": "Thermometer",
    "What is the capital of Canada?": "Ottawa",
    "Which animal is known for its black and white stripes?": "Zebra",
    "What is 7 x 8?": "56",
    "Who wrote Romeo and Juliet?": "Shakespeare",
    "What is the fastest land animal?": "Cheetah",
    "Which country gifted the Statue of Liberty to the USA?": "France",
    "What is the chemical symbol for water?": "H2O",
    "How many months are there in a year?": "12",
    "What is the largest planet in the solar system?": "Jupiter",
    "Which blood group is known as the universal donor?": "O Negative",
    "What is the capital of Germany?": "Berlin",
    "Which animal is known for carrying its house on its back?": "Turtle",
    "What is 144 divided by 12?": "12",
    "Who invented the light bulb?": "Thomas Edison",
    "What is the national flower of India?": "Lotus",
    "Which gas do humans need to breathe?": "Oxygen",
    "How many colors are there in a rainbow?": "7",
    "What is the capital of Russia?": "Moscow",
    "Which animal is the largest reptile?": "Crocodile",
    "What is 11 + 22?": "33",
    "Which continent is Egypt located in?": "Africa",
    "Who is known as the Father of Computers?": "Charles Babbage",
    "What is the tallest mountain in the world?": "Mount Everest",
    "Which fruit keeps the doctor away according to the saying?": "Apple",
    "What is the capital of China?": "Beijing",
    "Which animal produces wool?": "Sheep",
    "What is 13 x 6?": "78",
    "Which ocean lies between Africa and Australia?": "Indian Ocean",
    "What is the national bird of India?": "Peacock",
    "Which planet is known for supporting life?": "Earth",
    "What is the chemical symbol for sodium?": "Na",
    "How many players are there in a football team?": "11",
    "What is the capital of South Korea?": "Seoul",
    "Which animal is famous for its memory?": "Elephant",
    "What is 99 minus 45?": "54",
    "Who developed the theory of relativity?": "Albert Einstein",
    "Which instrument is used to look at stars?": "Telescope",
    "What is the largest internal organ in the human body?": "Liver",
    "Which country is famous for the Eiffel Tower?": "France",
    "What is the currency of Japan?": "Yen",
    "Which bird cannot fly?": "Ostrich",
    "What is 8 cubed?": "512",
    "Who painted the Starry Night?": "Vincent van Gogh",
    "Which country has the largest population?": "India",
    "What is the process by which plants make food?": "Photosynthesis",
    "Which organ helps us breathe?": "Lungs",
    "What is the capital of Italy?": "Rome",
    "Which animal is known as man's best friend?": "Dog",
    "What is 25 x 4?": "100"
}


if __name__ == '__main__':
    print("This is a file which contains questions for the quizz file")